[theme]
base = "light"
primaryColor = "#3B82F6"
backgroundColor = "#EBF2F7"
secondaryBackgroundColor = "#E2E8F0"
textColor = "#0F172A"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

