[theme]
base = "dark"
primaryColor = "#3B82F6"
backgroundColor = "#080C14"
secondaryBackgroundColor = "#0F172A"
textColor = "#F8FAFC"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
